desc finacialdata.financials;
select CName , Sector from financials order by CName;
select count(CName) as total_company  from financials;
select distinct(Sector) as unique_sector from financials order by Sector;
select CName  from financials where Sector ="Health Care" order by CName;
select CName from financials where Price > 100 ;
select CName, round(avg(Price),2) as avg_price from financials group by CName order by avg_price;
select min(MarketCap) as minimum_maketcap , max(MarketCap) as maximum_marketcap from financials ;
select round(sum(MarketCap),2) as total_marketcap from financials;
select CName, max(price) as highest_price from financials group by CName limit 1;
select CName ,min(Price) as lowest_price from financials group by CName  order by lowest_price limit 1;
select distinct(Sector),avg(Price_Earnings) as avererage_of_sec from financials group by Sector;
select Sector,avg(Price_Earnings) as avererage_of_sec from financials group by Sector order by avererage_of_sec desc;
select Sector,count(CName) as company_belogs_this_sec from financials group by Sector order by company_belogs_this_sec desc;
select Sector,count(CName) as company_belogs_this_sec from financials group by Sector  Having (company_belogs_this_sec) > 5 order by company_belogs_this_sec desc;
select CName ,DividendYield from financials where DividendYield > 2 ;
select CName,Price from financials order by Price Asc;
select CName,max(MarketCap) as top_5company from financials group by CName order by top_5company desc limit 5;
select CName,Price_Earnings from financials where Price_Earnings > 25 ;
select * from financials where CName LIKE '%Corp%'; 
select distinct Sector from financials;
select * from financials where CName LIKE 'a%';
select * from financials where CName LIKE '%inc';
select Sector, round(avg(Earnings_Share),2) as avg_earningsshare from financials group by Sector order by avg_earningsshare;
select * from financials where Price Between 50 and 150;
select * from financials order by DividendYield DESC;
select Sector ,sum(EBITDA) from financials group by Sector;
select Sector ,avg(Price_Sales) as avg_pricesales from financials group by Sector;
select Sector ,max(Price_Book)as highest_pricebook from financials group by Sector order by highest_pricebook desc;
select Sector ,min(DividendYield) as lowest_dividend from financials group by Sector order by lowest_dividend;
SELECT CName,MarketCap,(select round(avg(MarketCap),2) from financials) as avg_Marketcap from financials group by CName,MarketCap having MarketCap > avg_Marketcap order by MarketCap desc;
SELECT CName,MarketCap,(select round(avg(MarketCap),2) from financials) as avg_Marketcap from financials where MarketCap > (select avg(MarketCap) from financials) order by MarketCap desc;
select cname,marketcap,(select round(avg(DividendYield),2) from financials) as avg_dividendyeild from financials where DividendYield < (select round(avg(DividendYield),2) from financials) order by DividendYield desc;
select cname,52WeekLow,52WeekHigh,round((52WeekHigh - 52WeekLow),2) as diff_bet_high_low from financials order by diff_bet_high_low;  
select * from(select CName,Price,52WeekHigh,round(0.9 * 52WeekHigh ,2) as ninty_percent_high from financials) AS sub where Price >= ninty_percent_high order by Price desc;
select Cname,Price_Earnings,(select round(avg(Price_Earnings),2) from  financials) as avg_priceearnings from financials where Price_Earnings < (select avg(Price_Earnings) from  financials) order by Price_Earnings ASC;
select CName,Price_Book,(select count(Price_Book) from financials where Price_Book > 10) as Countedprice_book from financials where Price_Book > 10 order by Price_Book desc;
select Sector,sum(MarketCap) as total_marketcap from financials group by Sector order by total_marketcap  desc limit 3 ;
select * from financials where Price_Sales < 3 ;
select Sector,round(avg(DividendYield),2) as avg_dividend from financials group by Sector Having Sector = "Industrials";
select CName,EBITDA from financials where EBITDA > 1e10;
select cname,(MarketCap / EBITDA ) as marketcap_ratio from financials ;
select Sector , Price from financials order by  Sector asc , Price desc;
select Sector,round(sum(MarketCap),2)as total_marketcap from financials group by Sector;
select CName,length(CName) as name_length from financials where length(CName) > 15;
select concat(Symbol,'',CName) as combine_Symbol_CName  from financials;
select Sector, CName,max(EBITDA) as Largest_EBITDA from financials where Sector = "Health Care" group by CName ,Sector  order by Largest_EBITDA desc limit 1;
select Sector, avg(Price_Earnings) as AVERAGE_priceearnings from financials group by Sector having AVERAGE_priceearnings >20 ;
select Sector,count(CName) as count_companyname from financials group by sector order by count_companyname desc;
select Sector,CName ,Price from financials f1 where price >(select avg(Price) from financials f2 where f1.Sector = f2.Sector) order by Price asc;
select Sector,CName ,Price from financials where Price >(select avg(Price) from financials ) order by DividendYield desc;
select Sector,CName ,DividendYield from financials where DividendYield >(select avg(DividendYield) from financials ) order by DividendYield desc;
select Sector,CName ,DividendYield from financials f1 where DividendYield >(select avg(DividendYield) from financials f2 where f1.Sector = f2.Sector) order by Price asc;
select Sector,sum(MarketCap) as total_marketcap ,round(avg(MarketCap),2)as avg_marketcap from financials group by Sector;
select Sector ,count(CName)as Count_company from financials group by Sector order by Count_company desc limit 1;
select * from financials where Price_Book between 5 and 15;
select * from financials order by CName asc;
select CName,Price_Earnings from financials order by Price_Earnings desc limit 5;
select Sector,round(avg(Price_Earnings),2) as average_price from financials where Sector ="Information Technology";
select (52WeekHigh/Price)*100 as percentages from financials ;
select CName,sum(Price),sum(52WeekHigh) from financials where price = 52WeekHigh;
select CName,DividendYield from financials where DividendYield = 0;
select Sector,avg(Price_Book) as avg_pricebook from financials group by Sector order by avg_pricebook asc; 
select CName,Price_Sales from financials where Price_Sales between 2 and 4;
select CName ,SECFilings from financials where SECFilings like "%sec.gov%"; 
select count(CName) as word_company from financials where CName like  "%Company%";
select CName,Earnings_Share from financials where Earnings_Share < 1;
select Sector , max(Price) as highest_price from financials group by Sector order by highest_price desc;
select sector, min(Price) as lowest_price from financials group by Sector order by lowest_price ;
select Sector,round(sum(DividendYield),2) as total_dividendyeild from financials group by Sector order by total_dividendyeild desc;
select CName,Price,52WeekLow from financials where Price < 52WeekLow order by Price desc;
select Sector,count(CName) as total_company from financials group by Sector order by Sector asc;
select Sector,CName,MarketCap from financials group by Sector,CName,MarketCap having Sector = 'Industrials'order by MarketCap desc;
select round(avg(Price_Book),2) as average_pricebook from financials;
select Sector ,round(avg(Price_Earnings),2)as avg_priceearnings from financials group by Sector order by avg_priceearnings desc;
select Sector ,min(Earnings_Share) as min_earnings_sector , max(Earnings_Share) as max_earnings_sector from financials group by Sector;
select Sector ,round(avg(Price),2) as avg_price,round(avg(Price_Earnings),2) as avg_price_earnigs,round(avg(DividendYield),2) as avg_Dividend_Yield from financials group by Sector order by avg_Dividend_Yield desc;
-- select Sector,count(CName) as counted_company,round(avg(Price),2) as average_price from financials group by sector having Price > average_price order by average_price desc;
